### ISSUE TITLE
How to use schema.org extension like "auto.schema.org"?

### ISSUE THREAD

**Issue by comxd** [api-platform/schema-generator#116]
In my case, I need to use the [Motorcycle](https://auto.schema.org/Motorcycle) property from the auto.schema.org extension.

**Comment by jmverges** [comment]
Any info on this?

**Comment by MaelFr** [comment]
I think you should define the `vocabularyNamespace` parameter of your type. See [the doc](https://api-platform.com/docs/schema-generator/configuration#custom-schemas)

**Comment by comxd** [comment]
This not working:

```
    Motorcycle:
        vocabularyNamespace: "http://auto.schema.org/"
```

Error: **_[warning] Type "Motorcycle" cannot be found. Using "Thing" type to generate entity._**

**Comment by bgatellier** [comment]
Hi,

After a couple of hours trying to understand the documentation and where the different schema are located, here is the solution that worked for me :

```
# Explicitly list the RDFa references
rdfa:
    - 'https://schema.org/version/3.4/schema.rdfa'
    # https://schema.org/version/3.4/ext-pending.rdf file,
    # with additional missing <rdfs:comment></rdfs:comment> tags in order to make the parser works :/
    - './config/schema/ext-pending-3.4-fixed.rdf'
types:
    MonetaryAmount:
        vocabularyNamespace: 'http://schema.org/'
        properties:
            currency: ~
            value: { range: "Number" }
    MoneyTransfer:
        vocabularyNamespace: 'http://schema.org/'
        properties:
            amount: { range: "MonetaryAmount" }
    Person:
        vocabularyNamespace: 'http://schema.org/'
        properties:
            email: ~
            name: ~
```

**Comment by comxd** [comment]
Hi @bgatellier, in addition of your comment:

```
rdfa:
    #-  uri: "https://schema.org/docs/schema_org_rdfa.html" # Current version of Schema.org
    #    format: rdfa
    #-   uri: "https://raw.githubusercontent.com/schemaorg/schemaorg/master/data/ext/auto/auto.rdfa" # Experimental version of Schema.org extension: AUTO
    #    format: rdfa
    -   uri: "https://raw.githubusercontent.com/schemaorg/schemaorg/master/data/releases/3.4/all-layers.rdf" # Current version of Schema.org + all extensions
        format: rdf
    -   uri: "https://raw.githubusercontent.com/schemaorg/schemaorg/master/data/schema.rdfa" # Experimental version of Schema.org
        format: rdfa
```
