### ISSUE TITLE
error with asserting enums and typing

### ISSUE THREAD

**Issue by Selion05** [api-platform/schema-generator#131]
using api-platform 2.2.7 and following schema 
```
# api/config/schema.yaml
# The list of types and properties we want to use
fluentMutatorMethods: true
types:
    DayOfWeek:
        properties: []
    OpeningHoursSpecification:
        properties:
            opens: ~
            closes: ~
            dayOfWeek: ~
            validFrom: ~
            validThrough: ~
```
generates 

```
<?php

declare(strict_types=1);

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiProperty;
use ApiPlatform\Core\Annotation\ApiResource;
use App\Enum\DayOfWeek;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * A structured value providing information about the opening hours of a place or a certain service inside a place.\\n\\n The place is \_\_open\_\_ if the \[\[opens\]\] property is specified, and \_\_closed\_\_ otherwise.\\n\\nIf the value for the \[\[closes\]\] property is less than the value for the \[\[opens\]\] property then the hour range is assumed to span over the next day.
 *
 * @see http://schema.org/OpeningHoursSpecification Documentation on Schema.org
 *
 * @ORM\Entity
 * @ApiResource(iri="http://schema.org/OpeningHoursSpecification")
 */
class OpeningHoursSpecification
{

    /**
     * @var string[] the day of the week for which these opening hours are valid
     *
     * @ORM\Column(type="simple_array")
     * @ApiProperty(iri="http://schema.org/dayOfWeek")
     * @Assert\NotNull
     * @Assert\Choice(callback={"DayOfWeek", "toArray"}, multiple=true)
     */
    private $dayOfWeeks = [];

    public function getDayOfWeeks(): Collection
    {
        return $this->dayOfWeeks;
    }
}
```
## error1

```
  "hydra:description": "Return value of App\\Entity\\OpeningHoursSpecification::getDayOfWeeks() must be an instance of Doctrine\\Common\\Collections\\Collection, array returned",
```
fixed by changing
```
    public function getDayOfWeeks(): array
```
## error 2
```
  "hydra:description": "The Choice constraint expects a valid callback",
```
fixed by changing
```
     * @Assert\Choice(callback={"App\Enum\DayOfWeek", "toArray"}, multiple=true)
```
