### ISSUE TITLE
Bad assert @Assert\Choice in Enum

### ISSUE THREAD

**Issue by h3llr4iser** [api-platform/schema-generator#136]
I have a problem when generating an Enum class. I dont now if i am doing somthing wrong. The assert choice callback is generated without the enum namespace:

`@Assert\Choice(callback={"ItemAvailability", "toArray"})`
should be 
`@Assert\Choice(callback={"App\Enum\ItemAvailability", "toArray"})`

```
types:
  Offer:
    parent: false
    properties:
      availability: { range: ItemAvailability }
  ItemAvailability:
    parent: false
    properties: {}
```

```
class Offer
{
/**
     * @var string|null the availability of this item—for example In stock, Out of stock, Pre-order, etc
     *
     * @ORM\Column(nullable=true)
     * @Assert\Choice(callback={"ItemAvailability", "toArray"})
     * @ApiProperty(iri="http://schema.org/availability")
     */
    private $availability;
}

```

If I am doing correct I think the error could be in the next line

https://github.com/api-platform/schema-generator/blob/master/src/AnnotationGenerator/ConstraintAnnotationGenerator.php#L74

If I change the line 74 works ok.
```
$assert = sprintf('@Assert\Choice(callback={"%s", "toArray"}', $field['range']);
```

```
$assert = sprintf('@Assert\Choice(callback={"%s%s", "toArray"}', sprintf('%s\\%s', $this->config['namespaces']['enum'], $class['name']), $field['range']);
```
