### ISSUE TITLE
Integrate Relationships outside schema generator bundle for ownership

### ISSUE THREAD

**Issue by giorgioma** [api-platform/schema-generator#137]
Hello there! Fantastic project, I love it :+1: 

I have defined my custom AuthBundle with my entities inside App\Entity\AuthBundle without the schema generator and I am trying to generate my APIs schemas as follows:
```
namespaces:
     entity: App\Entity\ArticlesBundle

types:
     Articles:
          ....
          user: { range: App\Entity\AuthBundle\User, cardinality: (*..1) }

```
but I always get an undefined index
Is there something that I am missing from the documentation?

I was hoping for something similar to [this PR](https://github.com/api-platform/schema-generator/pull/115):
```
namspace:
     entity: ...
     alias:
        - { namespace: App\Entity\AuthBundle, resolvePath: src/Entity/AuthBundle }
```
this has been overwritten by a more general "prefix" in [this PR](https://github.com/api-platform/schema-generator/pull/121) that I am not fully understanding.

Is there any Yaml solution for implementing this?
Thank you :1st_place_medal:

**Comment by jlagneau** [comment]
Hello there!

I just gave a try to this and it works without troubles:

```yaml
types:
    User: # This is an identifier that you can use in the range below.
        namespaces:
            class: "App\\AuthBundle\\Entity"

    Article:
        namespaces:
            class: "App\\ArticleBundle\\Entity"
        properties:
            user: { range: User, cardinality: (*..1) } # Here you can use that User identifier.
            # Don't pass the whole namespace or it won't understand what you are referring
```

(I changed the directory name order to reflect Symfony bundle architecture but it shouldn't change anything as this schema generator is not aware of bundles).

Let me know if I understood something incorrectly.
