### ISSUE TITLE
How-to define custom property name

### ISSUE THREAD

**Issue by comxd** [api-platform/schema-generator#145]
In my case, I need to rename the schema.org field "accessCode" to "password":

```
User:
        guessFrom: "Person"
        properties:
            email: { unique: true, nullable: false }
            password: { nullable: false, guessFrom: "accessCode" }
```

The `guessFrom` option is not recognized.
