### ISSUE TITLE
generationStrategy not working as documented

### ISSUE THREAD

**Issue by ruiisidro** [api-platform/schema-generator#157]
In the schema.yaml having 

```
    Brand:
        properties:
            id:
                generationStrategy: "uuid"
                writable: false 
```

leads to 

> In ArrayNode.php line 331:
> 
>   Unrecognized option "generationStrategy" under "config.types.Brand.properties.id". Available options are "cardinality", "columnPrefix", "embedded", "groups", "nullable
  ", "ormColumn", "range", "readable", "relationTableName", "unique", "writable".
