### ISSUE TITLE
Schema generator - generate class not resource

### ISSUE THREAD

**Issue by Arkowsky** [api-platform/schema-generator#159]
I have in my schema.yaml file structure like below PostalAddress:

```
types:
...
  PostalAddress:
    properties:
      addressCountry: { range: Text }
      addressLocality: { range: Text }
      addressRegion: { range: Text }
      postOfficeBoxNumber: { range: Text }
      postalCode: { range: Text }
      streetAddress: { range: Text }
...
```
after generate I receive:

```
/**
 * The most generic type of item.
 *
 * @see http://schema.org/Thing Documentation on Schema.org
 *
 * @ORM\Entity
 * @ApiResource(iri="http://schema.org/Thing")
 */
class PickupPoint
{
```

I don't want to have api resource for that:

![image](https://user-images.githubusercontent.com/19975089/52699671-9db45b80-2f76-11e9-8d1f-7300aae575b6.png)

Is there any way to do this?
