### ISSUE TITLE
same table name for two relations

### ISSUE THREAD

**Issue by ZeBigDuck** [api-platform/schema-generator#17]
Hi!

I'm experiencing issue with php schema.

I've got following entity:

```yml
  Organization:
    properties:
      contactPoint: { range: Person }
      member: { range: Person, cardinality: (1..*) }
```

Which causes the following error at generation : 

>   The table with name 'api.organization_person' already exists.  

Is there an option to force relation table name ?

Thank you
