### ISSUE TITLE
The inheritance of entities and the namespaces

### ISSUE THREAD

**Issue by yelmontaser** [api-platform/schema-generator#24]
Hello everyone,

One little example is worth a thousand words:

```yml
Person:
    namespaces:
        class: AppBundle\Entity\SchemaOrg
    properties:
        gender: ~
        givenName: ~
        familyName: ~
        ....

Profile:
    properties:
        ....
```
Entity generated : 

````php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
....

/**
 * @ORM\Entity
 */
class Profile extends Person
{
    /**
     * @var int
     * 
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    ...
```

The generator does not take into account the Person namespace, it lacks the use operator
```php
use AppBundle\Entity\SchemaOrg\Person
```
it's a bug?

Thanks
