### ISSUE TITLE
Enum Class Generation for schema.org/OrderStatus not working

### ISSUE THREAD

**Issue by stiivo** [api-platform/schema-generator#400]
**API Platform version(s) affected**: 3.0.8  Generator: 5.2.0

**Description**  

Enum generation not working for schema.org/OrderStatus
Instead OrderStatus becomes a normal Entity

**How to reproduce**  
```yaml
types:
  Thing:
    properties:
      gender: { range: "https://schema.org/GenderType" }
      orderStatus: { range: "https://schema.org/OrderStatus" }
  GenderType:
    properties:
      gender: [ ]
  OrderStatus:
    properties:
      orderStatus: [ ]
```

``
$ php vendor/bin/schema generate config/schema.yaml
``
