### ISSUE TITLE
Declare multiple operations

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/schema-generator#405]
**API Platform version(s) affected**: ^3.1

**Description**  
It's not possible to declare multiple operations using the same class:
```yaml
operations:
  Post:
    uriTemplate: /books/{bookId}/borrow
  Post:
    uriTemplate: /books/{bookId}/return
```
In API Platform 3.*, to prevent this limitation, it is possible to declare the operations as following:
```yaml
operations:
  - class: ApiPlatform\Metadata\Post
    uriTemplate: /books/{bookId}/borrow
  - class: ApiPlatform\Metadata\Post
    uriTemplate: /books/{bookId}/return
```
But the code generated by the Schema Generator is invalid:
```php
#[ApiResource(
    operations: [
        new 0(class: 'ApiPlatform\Metadata\Post', uriTemplate: '/books/{bookId}/borrow'),
        new 1(class: 'ApiPlatform\Metadata\Post', uriTemplate: '/books/{bookId}/return'),
```

**How to reproduce**  
Declare the following configuration in the `schema.yaml` file:
```yaml
types:
    BookOffer:
        guessFrom: "Book"
        attributes:
            - ApiResource:
                types: [ "https://schema.org/Book" ]
        operations:
            - class: "ApiPlatform\\Metadata\\GetCollection"
            - class: "ApiPlatform\\Metadata\\Get"
```
Then, run the Schema Generator: `vendor/bin/schema generate src/ config/schema.yaml -vv`

**Possible Solution**  
Support both formats declared above.

**Additional Context**
