### ISSUE TITLE
Full Schema generation incorrect

### ISSUE THREAD

**Issue by aaron-harding** [api-platform/schema-generator#63]
Hi,

When attempting to generate the entire schema as described in the documentation:

> Without configuration file, the tool will build the entire Schema.org vocabulary. If no properties are specified for a given type, all its properties will be generated.

No properties are generated in any of the Entities. Example config:

``` YAML
rdfa:
  - vendor/api-platform/schema-generator/tests/data/schema.rdfa

# The PHP namespace of generated entities
namespaces:
  # The namespace of the generated entities
  entity: App\Schema\Entity
  # The namespace of the generated enumerations
  enum: App\Schema\Enum
  # The namespace of the generated interfaces
  interface: App\Schema\Model

annotationGenerators:
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\PhpDocAnnotationGenerator
```

This generates all schema Entities and Enum but the entities are only generated with the ID setters/getters. Specifying each type individually creates the remaining properties as expected.

Possibly the same issue as #62, however the solution to use the test schema.rdfa does not work in my example.
