### ISSUE TITLE
[enhancement] don't make abstract classes and embeddables api resources

### ISSUE THREAD

**Issue by Evertt** [api-platform/schema-generator#72]
Right now if I have this `schema.yml`

```yaml
types:
    Thing:
        properties:
            name: ~

    Person:
        properties:
            familyName: ~

    Country:
        parent: false
        embeddable: true
        properties:
            address: { range: "Text" }

    PostalAddress:
        parent: false
        properties:
            addressCountry: { range: "Country", embedded: true, columnPrefix: false }
```

It will generate all the entities and all entities are marked as an api resource in the class annotations. The only problem is that you don't want `Thing` and `Country` to be api resources. `Thing` is an abstract class so it can't even be initialized. And since `Country` is an embeddable it isn't linked to any database table so you can never fetch any countries form the api.
