### ISSUE TITLE
[enhancement] generate entity constructors with all non-nullable properties

### ISSUE THREAD

**Issue by Evertt** [api-platform/schema-generator#73]
If my `schema.yml` says this:

```yaml
product:
  parent: false
  properties:
    name: { nullable: false }
```

Then I would love it if my `Product.php` then contains a constructor function which requires the `$name` property. That way you can guarantee when if I or another developer wants to initialize a new `Product`, that it will be a valid entity right after initialization.
